version: '3.8'
services:
  backend-nginx:
    build:
      context: ./backend/docker/development
      dockerfile: nginx.docker
    volumes:
      - ./backend:/app
    depends_on:
      - php-fpm
    ports:
      - "8081:80"

  php-fpm:
    build:
      context: ./backend/docker/development
      dockerfile: php-fpm.docker
    volumes:
      - ./backend:/app
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true client_host=127.0.0.1 log_level=0 client_port=9003'
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    depends_on:
      - mysql

  php-cli:
    build:
      context: ./backend/docker/development
      dockerfile: php-cli.docker
    volumes:
      - ./backend:/app
      - composer:/root/.composer/cache
    environment:
      XDEBUG_CONFIG: 'discover_client_host=true client_host=127.0.0.1 log_level=0 client_port=9003'
      PHP_IDE_CONFIG: "serverName=Docker"
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "6603:3306"


volumes:
  composer:



